openimsdk/openim-sdk-core

go.mod
go.sum
internal/common/alioss.go
internal/common/alioss_test.go
internal/login/init_login.go
pkg/constant/server_api_router.go
pkg/server_api_params/oss_api_struct.go

新增支持ali oss

---

CONTRIBUTING.md
Makefile
internal/cache/cache.go
open_im_sdk/signaling.go

Signed-off-by: Xinwei Xiong(cubxxw) <3293172751nss@gmail.com>
Fix: #53
Link: #50

docs: design contributor documentation

---

.vscode/launch.json
Makefile
go.mod
go.sum
internal/conversation_msg/create_message.go
wasm/indexdb/group_member_model.go

Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com></br>
Fixes #

style: some details

---

.gitignore
internal/cache/cache.go
internal/conversation_msg/conversation_msg.go
internal/conversation_msg/conversation_notification.go
internal/conversation_msg/delete.go
internal/conversation_msg/max_seq_recorder.go
internal/conversation_msg/message_controller.go
internal/conversation_msg/progress.go
internal/conversation_msg/read_drawing.go
internal/conversation_msg/revoke.go
internal/conversation_msg/sdk.go
internal/conversation_msg/sync.go
internal/interaction/long_conn_mgr.go
internal/interaction/long_connection.go
internal/signaling/signaling.go
internal/third/push.go
open_im_sdk/file.go
open_im_sdk_callback/callback_go_sdk.go
pkg/common/trigger_channel.go
pkg/constant/constant.go
pkg/db/chat_log_model_v3.go
pkg/db/model_struct/data_model_struct.go
pkg/sdkerrs/code.go
pkg/sdkerrs/error.go
pkg/sdkerrs/predefine.go
sdk_struct/sdk_struct.go
testv2/empty_test.go
testv2/sync_test.go

feat: main test

---

testv3/funcation/config.go
testv3/funcation/friend.go
testv3/funcation/login.go
testv3/funcation/register.go
testv3/funcation/reliability.go
testv3/funcation/sendMessage.go
testv3/login_test.go
testv3/register_test.go

feat: add test function about user login

---

internal/friend/friend.go

fix bug: add friend sync both recv and send request

---

internal/conversation_msg/sdk.go
pkg/content_type/content_type.go

fix: msg file Content-Type

---

go.mod
go.sum
internal/conversation_msg/image.go
internal/conversation_msg/sdk.go
internal/interaction/long_conn_mgr.go
pkg/content_type/content_type.go
testv3/funcation/util.go
testv3new/cmd/main.go
testv3new/pressure_test.go
testv3new/pressure_tester.go
testv3new/register_manager.go
testv3new/testcore/lightweight.go

fix: ws conn token error and image parse

---

build.cmd
start.bat
testv3new/pressure_test.go
testv3new/pressure_tester.go
testv3new/test_struct.go

test program

---

cmd/main.go
internal/full/full.go
internal/full/open_im_sdk_full.go
internal/login/init_login.go
pkg/db/db_interface/databse.go
pkg/db/group_member_model.go
pkg/utils/utils.go
test/t_friend_sdk.go

fix bug: user update faceURL and nickName not exist

---

internal/conversation_msg/progress.go
open_im_sdk_callback/callback_client.go

fix: can't compile

---

internal/conversation_msg/sdk.go

feat: server thumbnail

---

internal/group/notification.go

fix: group invited user synced all group members

---

internal/conversation_msg/sdk.go
internal/group/notification.go
testv2/config.go
testv2/init.go

fix: group entry notification processing

---

internal/conversation_msg/delete.go
pkg/sdkerrs/code.go
pkg/sdkerrs/predefine.go

fix: delete send failed msg

---

internal/conversation_msg/conversation_msg.go

old read msg status is not true

---

internal/conversation_msg/read_drawing.go

fix bug: clear empty conversation

---

cmd/main.go
internal/cache/cache.go
internal/conversation_msg/conversation_msg.go
internal/conversation_msg/sync.go
internal/full/full_model.go
internal/group/group.go
test/config.go
test/login.go

feat: batch sync users and groups

---

internal/login/init_login.go

fix bug: sync conversations may panic

---

internal/cache/cache.go
internal/group/group.go

fix bug: sync users

---

cmd/main.go
go.mod
go.sum
internal/conversation_msg/conversation.go
internal/conversation_msg/conversation_msg.go
internal/conversation_msg/conversation_notification.go
internal/conversation_msg/sync.go

new feat: new con sync unread

---

internal/user/sdk.go
internal/user/user.go
open_im_sdk/user.go

Optimize userid

---

open_im_sdk/user.go

refactor: Optimize cross-language passing parameters

---

internal/conversation_msg/conversation_msg.go
internal/conversation_msg/conversation_notification.go
internal/conversation_msg/sdk.go

private chat lock

---

internal/conversation_msg/sdk.go

chore: default thumbnail size

---

open_im_sdk/user.go
wasm/wasm_wrapper/wasm_user.go
ws_wrapper/ws_local_server/ws_user.go

fix:The sdk about subscribing to online status in wasm is missing

---

internal/full/open_im_sdk_full.go
pkg/db/db_init.go
pkg/db/db_interface/databse.go
pkg/db/model_struct/data_model_struct.go
pkg/db/stranger_model.go
pkg/server_api_params/public_struct.go
wasm/indexdb/init.go
wasm/indexdb/stranger_model.go
wasm/indexdb/user_model.go

feat:Caching of personal information of strangers in group chats 

---

pkg/db/stranger_model.go
wasm/indexdb/user_model.go

feat: add build js for #304

---

open_im_sdk/user.go
pkg/db/stranger_model.go
wasm/indexdb/user_model.go

fix:Normal storage of stranger information

---

Makefile
docs/.generated_docs
pkg/version/README.md
pkg/version/base.go
pkg/version/helpers.go
pkg/version/helpers_test.go
pkg/version/types.go
pkg/version/version.go

Signed-off-by: Xinwei Xiong(cubxxw-openim) <3293172751nss@gmail.com><br>
/kind documentation
/kind feature
Resolves #116, resolves #315
no
```bash
make ios
```
server version

feat: set openim sdk version

---

internal/conversation_msg/conversation_msg.go

fix: repeated trigger conversation changed.

---

internal/conversation_msg/conversation_msg.go
internal/group/notification.go
pkg/db/group_member_model.go
pkg/db/model_struct/data_model_struct.go

fix: get group member list order by join time asc.

---

internal/conversation_msg/conversation_msg.go
internal/full/open_im_sdk_full.go
internal/group/notification.go
open_im_sdk/user.go
pkg/db/group_member_model.go
pkg/db/model_struct/data_model_struct.go
pkg/server_api_params/public_struct.go
wasm/cmd/main.go
wasm/wasm_wrapper/wasm_user.go

refactor: rename get user info from cache.

---

go.mod
go.sum
internal/group/sdk.go
internal/login/init_login.go
internal/third/log.go
internal/third/log_test.go
internal/third/push.go
open_im_sdk/third.go
pkg/ccontext/context.go
pkg/ccontext/context_test.go
pkg/constant/server_api_router.go
pkg/sdk_params_callback/third_sdk_struct.go

feat: addlog

---

internal/conversation_msg/conversation_msg.go
internal/conversation_msg/create_message.go
internal/full/open_im_sdk_full.go
internal/group/notification.go
open_im_sdk/conversation_msg.go
open_im_sdk/user.go
pkg/db/group_member_model.go
pkg/db/model_struct/data_model_struct.go
pkg/server_api_params/public_struct.go
wasm/cmd/main.go
wasm/wasm_wrapper/wasm_user.go

feat: send mesasge by url add source path.

---

internal/conversation_msg/read_drawing.go
pkg/db/conversation_model.go

fix: message unread count remove when user not in group.

---

internal/conversation_msg/conversation_msg.go

Fix msgHandleByContentType, set msg.AdvancedTextElem.

---

internal/user/sync.go

fix: online status changed.

---

internal/user/sync.go
wasm/cmd/main.go

fix: online status change.

---

internal/conversation_msg/sdk.go
internal/user/sync.go
wasm/cmd/main.go

fix: send time update.

---

internal/interaction/msg_sync.go

fix: do not pull notifications when app reinstalled.

---

internal/interaction/msg_sync.go

fix: pull message unread count remove.

---

internal/conversation_msg/conversation.go
internal/conversation_msg/sdk.go
pkg/sdk_params_callback/conversation_msg_sdk_struct.go

fix: search message sort and bug fix.

---

internal/conversation_msg/conversation_msg.go
internal/interaction/long_conn_mgr.go
open_im_sdk/userRelated.go
wasm/event_listener/caller.go

fix: change init logout status order.

---

internal/conversation_msg/conversation.go

fix: add picture and video search.

---

internal/business/business.go
internal/business/open_im_sdk_business.go
internal/conversation_msg/conversation_msg.go
internal/conversation_msg/conversation_notification.go
internal/conversation_msg/delete.go
internal/conversation_msg/read_drawing.go
internal/conversation_msg/revoke.go
internal/conversation_msg/sdk.go
internal/friend/friend.go
internal/group/group.go
internal/group/notification.go
internal/group/sync.go
internal/user/sync.go
internal/user/user.go
open_im_sdk/caller.go
open_im_sdk/userRelated.go
open_im_sdk_callback/callback_go_sdk.go

refactor: using closures, can allow the listener to be overridden multiple times.

---

internal/interaction/long_conn_mgr.go
internal/third/log.go
internal/third/log_test.go
internal/third/progress.go
internal/third/third.go
internal/third/zip.go
internal/util/post.go
open_im_sdk/apicb.go
open_im_sdk/third.go
open_im_sdk/userRelated.go
open_im_sdk_callback/callback_client.go
pkg/ccontext/context.go
sdk_struct/sdk_struct.go

feat: token callback and upload log

---

internal/conversation_msg/conversation_notification.go
internal/conversation_msg/read_drawing.go
open_im_sdk/userRelated.go

fix: conversation's latestMsg struct unmarshal err type.

---

internal/interaction/reconnect.go

fix: add re conn index increment.

---

internal/conversation_msg/conversation_msg.go
internal/conversation_msg/message_controller.go
internal/conversation_msg/sdk.go
internal/interaction/long_conn_mgr.go
internal/interaction/reconnect.go

fix: message status handle in weak net.

---

internal/group/group.go
internal/group/notification.go
internal/interaction/long_conn_mgr.go
internal/interaction/ws_js.go

fix: wasm parse data.

---

internal/group/sdk.go
pkg/db/db_interface/databse.go
pkg/db/super_group_model.go

<br>
Fixes #https://github.com/openimsdk/open-im-sdk-flutter/issues/131

fix: remove some code to avoid creating group errors..

---

internal/conversation_msg/sdk.go
internal/group/sdk.go
pkg/db/db_interface/databse.go
pkg/db/super_group_model.go

fix: find message add local Ex.

---

internal/conversation_msg/read_drawing.go
internal/conversation_msg/sdk.go
internal/group/sdk.go
pkg/db/db_interface/databse.go
pkg/db/super_group_model.go
pkg/sdkerrs/code.go
pkg/sdkerrs/predefine.go

fix: notification unread conversation update.

---

internal/group/notification.go

fix: GroupApplicationRejectedNotification trigger problem

---

internal/conversation_msg/sdk.go
open_im_sdk/conversation_msg.go
testv2/conversation_test.go
wasm/cmd/main.go
wasm/wasm_wrapper/wasm_conversation_msg.go

fix: add the parameter "isOnlineOnly" to the "sendMessage" method.

---

internal/conversation_msg/conversation_msg.go
internal/conversation_msg/sdk.go
open_im_sdk/conversation_msg.go
testv2/conversation_test.go
wasm/cmd/main.go
wasm/wasm_wrapper/wasm_conversation_msg.go

fix: online only message to trigger new messages.

---

internal/interaction/long_conn_mgr.go
open_im_sdk/apicb.go
open_im_sdk_callback/callback_client.go
test/t_conversation_msg.go
test/t_friend_sdk.go
wasm/event_listener/listener.go

Release v3.5 syncheartbeat

---

internal/util/post.go

fix: reduce http request timeout.

---

internal/conversation_msg/message_controller.go

fix: conversation latestMsg update message status when seq fill.

---

Makefile

Fixes #
remove intrusive command about git hooks.

remove intrusive command.

---

open_im_sdk/friend.go
open_im_sdk/group.go

comment not use SDK core interface

comment not use SDK core interface

---

go.mod
go.sum
internal/interaction/long_conn_mgr.go
open_im_sdk/apicb.go

fix: token cb update.

---

internal/interaction/msg_sync.go
pkg/db/chat_log_model_v3.go
pkg/db/conversation_model.go
pkg/db/db_interface/databse.go

fix:optimize login

---

internal/conversation_msg/conversation_msg.go
internal/group/group.go
internal/group/notification.go
internal/group/sdk.go
internal/group/sync2.go
internal/incrversion/option.go
internal/user/sync.go
pkg/db/app_version.go
pkg/db/db_init.go
pkg/db/user_model.go
pkg/db/version_sync.go

#
fix: solve multiplatform sync concurrency error.

fix: solve multiplatform sync concurrency error.

---

wasm/indexdb/version_sync.go

fix: solve nil pointer in wasm.

fix: solve nil pointer in wasm.

---

pkg/db/group_member_model.go

fix: update uncorrect statement.

fix: update uncorrect statement.

---

pkg/db/version_sync.go

fix: update condition return args in getVersionSync.

fix: update condition return args.

---

internal/interaction/long_conn_mgr.go
internal/interaction/long_connection.go
internal/interaction/ws_default.go
internal/interaction/ws_js.go

feat: update pingpongHandler.

---

internal/group/sdk.go

fix: update incr sync timing logic when quit group.

fix: update incr sync timing logic when quit group.

---

internal/group/notification.go
internal/group/sdk.go

fix: solve group concurrency issue.

fix: solve group concurrency issue.

---

internal/group/sdk.go

fix: solve concurrecy issues in group.

fix: solve concurrecy issues in group.

---

internal/conversation_msg/conversation_notification.go
open_im_sdk/userRelated.go
pkg/common/trigger_channel.go
pkg/constant/constant.go

feat: implement syncData when App not isBackground.

---

internal/conversation_msg/conversation_msg.go
internal/friend/friend.go
internal/interaction/long_conn_mgr.go
internal/util/post.go
pkg/datafetcher/datafetcher.go
pkg/syncer/syncer.go

fix: change limit int type avoid overflow and group member sorted.

---

internal/third/log.go
open_im_sdk/third.go
testv2/third_test.go

Fixes #
feat: log support system type and ex

feat: log support system type and ex

---

sdk_struct/sdk_struct.go

feat: protocol

---

internal/conversation_msg/conversation_msg.go
internal/conversation_msg/conversation_notification.go
internal/conversation_msg/message_check.go
pkg/constant/constant.go
sdk_struct/sdk_struct.go

feat: update msg Sync by Reinstalled trigger const.

feat: update msg Sync by Reinstalled trigger const.

---

internal/third/log.go
internal/third/third.go
open_im_sdk/third.go
testv2/third_test.go

Fix logs upload

---

integration_test/README.md
integration_test/internal/manager/group_manager.go
integration_test/internal/manager/manager.go
integration_test/internal/manager/relation_manager.go
integration_test/internal/manager/user_manager.go
integration_test/internal/pkg/initialization/config.go
integration_test/internal/pkg/initialization/flag.go
integration_test/internal/pkg/sdk_user_simulator/listener.go
integration_test/internal/pkg/sdk_user_simulator/user.go
integration_test/internal/pkg/utils/group.go
integration_test/internal/pkg/utils/user.go
integration_test/internal/process/checker/group.go
integration_test/internal/process/checker/model.go
integration_test/internal/process/v1.go
integration_test/internal/sdk/group.go
integration_test/internal/sdk/sdk.go
integration_test/internal/vars/cmd.go
integration_test/internal/vars/config.go
integration_test/internal/vars/group.go
integration_test/internal/vars/limit.go
integration_test/internal/vars/user.go
integration_test/main.go

feat: test

---

internal/third/log.go
internal/third/third.go
open_im_sdk/init_login.go
open_im_sdk/userRelated.go
pkg/constant/constant.go

refactor: remove unuse sdk version field.

refactor: remove unuse sdk version field.

---

internal/third/log.go
open_im_sdk/third.go

Fixes #
feat: log can add line and delete old logs

feat: log can add line and delete old logs

---

internal/third/log.go

Fixes #
fix: set scanner buffer

fix: set scanner buffer

---

internal/group/sdk.go

fix: filter Invalid.

---

.github/workflows/ISSUE_TEMPLATE/bug-report.yaml
.github/workflows/link-pr.yml
internal/group/sdk.go

deps: update bug-report.yaml

---

pkg/db/admin_group_request_model.go
pkg/db/black_model.go
pkg/db/chat_log_model.go
pkg/db/chat_log_reaction_extension_model.go
pkg/db/conversation_model.go
pkg/db/db_init.go
pkg/db/err_chat_log_model.go
pkg/db/friend_model.go
pkg/db/friend_request_model.go
pkg/db/group_member_model.go
pkg/db/group_model.go
pkg/db/group_request_model.go
pkg/db/notification_model.go
pkg/db/sending_messages_model.go
pkg/db/seq_data_model.go
pkg/db/stranger_model.go
pkg/db/super_group_chat_log_model.go
pkg/db/super_group_model.go
pkg/db/table_master.go
pkg/db/temp_cache_chat_log_model.go
pkg/db/upload_model.go
pkg/db/user_command.go
pkg/db/user_model.go
pkg/db/version_sync.go

Fixes #
feat: change lock to global db lock

feat: change lock to global db lock

---

internal/incrversion/option.go

fix: remove redundant func.

---

internal/interaction/long_conn_mgr.go
internal/interaction/msg_sync.go
open_im_sdk/userRelated.go
pkg/common/trigger_channel.go

feat: implement panic recovery.

feat: implement panic recovery.

---

internal/conversation_msg/conversation_msg.go
internal/conversation_msg/conversation_notification.go
internal/conversation_msg/read_drawing.go
internal/conversation_msg/sync.go
internal/interaction/msg_sync.go
pkg/common/trigger_channel.go
pkg/db/model_struct/data_model_struct.go

fix: Bug fix for clearing unread messages.

---

internal/friend/sdk.go
internal/friend/sync.go

fix: solve AddFriend uncorrect call.

fix: solve AddFriend uncorrect call.

---

go.mod
go.sum
internal/group/sdk.go
pkg/constant/server_api_router.go

feat: update set GroupInfo logic.

---

internal/conversation_msg/sync.go
pkg/constant/constant.go
pkg/db/db_init.go

refactor: mv GetConversationsHasReadAndMaxSeq from HTTP to Websocket.

---

internal/conversation_msg/api.go
pkg/constant/constant.go
pkg/db/conversation_model.go

refactor: fix error handling in SendMessage function

---

internal/group/incremental_sync.go
pkg/db/version_sync.go

Fixes #
fix: IncrSyncGroupAndMember error

fix: IncrSyncGroupAndMember error

---

go.mod
go.sum
internal/group/api.go
internal/group/server_api.go
pkg/api/api.go
test/group_test.go

refactor: update setGroupInfoEx field.

---

.github/workflows/comment-check.yml

 refactor: Exclude files and directories from non-English comment check

---

.github/workflows/update-version-file-on-release.yml

feat: implement update version file on release.

---

internal/group/group.go
internal/group/notification.go

Fixes https://github.com/openimsdk/openim-sdk-core/issues/706
feat: change level del request

feat: change level del request

---

integration_test/internal/manager/manager.go
integration_test/internal/manager/user_manager.go
msgtest/module/manager.go
pkg/api/api.go
test/init.go

Fixes #
test: fix get user token

test: fix get user token

---

go.mod
go.sum
integration_test/internal/manager/manager.go
integration_test/internal/manager/user_manager.go
msgtest/module/manager.go
msgtest/module/user_manager.go
pkg/api/api.go
test/init.go

refactor: update userToken to getAdminToken

---

version/version.go

Fixes #
fix: remove version space

fix: remove version space

---

Makefile
integration_test/internal/pkg/reerrgroup/errgroup.go
wasm/cmd/static/wasm_exec.js

fix: remove duplicate License.

---

internal/conversation_msg/api.go
open_im_sdk/conversation_msg.go
pkg/db/conversation_model.go
pkg/db/db_interface/databse.go
test/config.go
test/conversation_test.go
wasm/cmd/main.go
wasm/indexdb/conversation_model.go
wasm/wasm_wrapper/wasm_conversation_msg.go

Fixes #742
feat: mark all conversation as read

feat: mark all conversation as read

---

.github/workflows/cleanup-after-milestone-prs-merged.yml
.github/workflows/merge-from-milestone.yml

build: implement create Pre-release PR from Milestone.

---

internal/conversation_msg/conversation_msg.go
internal/user/api.go
internal/user/full_sync.go

fix: improve batchUserFaceURLandName logic.

---

.github/workflows/cleanup-after-milestone-prs-merged.yml
internal/conversation_msg/api.go

fix: fix temp file don't remove when upload file.

---

internal/group/cache.go

Fixes #
fix: GetGroupMembersInfoFunc return key

fix: GetGroupMembersInfoFunc return key

---

internal/conversation_msg/api.go
internal/interaction/msg_sync.go
pkg/db/model_struct/data_model_struct.go

fix: Change check reinstall logic

---

wasm/indexdb/chat_log_model.go

fix: deleting the last message in a conversation will prompt failure

---

internal/conversation_msg/revoke.go

fix: solve uncorrect log in revoke handle.

---

internal/conversation_msg/api.go

fix: solve uncorrect delete temp file.

---

.github/workflows/merge-from-milestone.yml

build: remove uncorrect schedule.

---

tools/changelog/changelog.go

build: add bot PR merged filter.

---

internal/interaction/msg_sync.go

Fix：Change check reinstall logic

---

pkg/db/chat_log_model.go

fix: create index failed when table name has `-`.

---

internal/interaction/msg_sync.go

fix: change errs to custom errs avoid sdk panic.

---

internal/conversation_msg/api.go
internal/conversation_msg/message_check.go
internal/user/api.go
internal/user/user.go
pkg/cache/manager.go

fix: login user's info maybe empty when app reinstall.

---

internal/conversation_msg/conversation.go
internal/conversation_msg/message_check.go

fix: add server isEnd determination criteria for message retrieval.

---

internal/conversation_msg/conversation.go

fix: search message do not filter voice message when keyword is empty.

---

internal/relation/api.go

fix: Add black api add lock

---

.github/workflows/go-build-test.yml

Fixes https://github.com/openimsdk/open-im-server/issues/2974

fix: cicd notification.yml changed

---

internal/conversation_msg/api.go
internal/conversation_msg/conversation.go
internal/conversation_msg/conversation_msg.go
internal/conversation_msg/conversion.go
internal/conversation_msg/message_check.go
internal/user/user.go
open_im_sdk/conversation_msg.go
pkg/cache/conversation_seq_cache.go
pkg/cache/user_cache.go
pkg/sdk_params_callback/conversation_msg_sdk_struct.go
pkg/sdkerrs/code.go
pkg/sdkerrs/predefine.go
test/create_msg_test.go

feat: add a function to quickly retrieve the context messages for a given message.

---

internal/conversation_msg/api.go
internal/conversation_msg/conversation.go
open_im_sdk/conversation_msg.go
pkg/cache/cache.go
pkg/cache/conversation_seq_cache.go
wasm/cmd/main.go
wasm/wasm_wrapper/wasm_conversation_msg.go

refactor: remove fetch messages instead of search message clear cache.

---

.github/workflows/go-build-test.yml
.github/workflows/merge-from-milestone.yml

build: improve workflows contents.

---

open_im_sdk/conversation_msg.go

Fixes #
getConversationIDBySessionType 获取的字符串带转义符号,\"sadfljksad\"

fix: GetConversationIDBySessionType 返回的字符串带转义符

---

README.md
README_zh-CN.md
docs/gomobile-android-ios-setup-cn.md

docs:  readme doc update and add doc for gomobile compile sdk core.

---

.github/workflows/merge-from-milestone.yml

build: fix merge failed when conflict.

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/other.yml
.github/workflows/auto-invite-comment.yml
CONTRIBUTING.md
README.md
README_zh-CN.md
scripts/template/footer.md.tmpl

chore: update slack link in repo.

---

internal/user/user.go

fix: sync self conversation's avatar when user's info changed.

---

internal/conversation_msg/message_check.go

fix: directly deduplicate the messages pulled from the server.

---

internal/conversation_msg/revoke.go

fix: get group member info maybe failed.

---

.github/workflows/go-build-test.yml
integration_test/internal/config/config.go

fix: change secret && cicd modify secret

---

open_im_sdk/userRelated.go
pkg/sdkerrs/code.go

feat: sdk not init and not login code

---

internal/group/api.go
open_im_sdk/group.go
wasm/cmd/main.go
wasm/wasm_wrapper/wasm_group.go

feat: CheckLocalGroupFullSync & CheckGroupMemberFullSync

---

open_im_sdk/conversation_msg.go

fix: solve incorrect args in CreateMsg method.

---

go.mod
go.sum
internal/interaction/long_conn_mgr.go
internal/interaction/ws_js.go
wasm/event_listener/callback_writer.go

fix: use a custom close code for javascript websocket active disconnection to prevent close failures, according to the WebSocket RFC documentation.

---

internal/user/full_sync.go

fix: SyncLoginUserInfo

---

internal/interaction/ws_js.go

feat: wasm support application layer ping

---

go.mod
go.sum
internal/conversation_msg/incremental_sync.go
internal/conversation_msg/notification.go
internal/group/full_sync.go
internal/group/incremental_sync.go
internal/interaction/long_conn_mgr.go
internal/interaction/ws_js.go
internal/relation/incremental_sync.go
internal/relation/sync.go
internal/user/full_sync.go
open_im_sdk/apicb.go
open_im_sdk/userRelated.go
wasm/event_listener/callback_writer.go

fix: failure to clear @ tags in conversations, group member synchronization errors, and friend list synchronization anomalies,due to concurrency.

---

internal/interaction/long_conn_mgr.go
msgtest/module/msg_sender.go
open_im_sdk/userRelated.go
sdk_struct/sdk_struct.go

V3.8.4 watch dog

---

internal/conversation_msg/notification.go
internal/group/notification.go
internal/relation/notification.go
internal/user/notification.go

* feat: code adjustment
* feat: Cmd2Value carry caller
* feat: Cmd2Value carry caller
* feat: Cmd2Value carry caller
* feat: Cmd2Value carry caller
* fix: SearchLocalMessages no such table
* fix: optimize the freeze caused by too many friends and group applications
* feat: optimize notification triggering
(cherry picked from commit 2d65e55e470767539e14a12282612ed757d54e90)
Fixes #926

feat: optimize notification triggering (#927)

---

go.mod
go.sum
internal/group/filter.go
internal/group/full_sync.go
internal/group/group.go
internal/group/notification.go
pkg/network/http_client.go
test/config.go

fix: repeat notification trigger

---

internal/group/group.go

fix: group request trigger

---

msgtest/module/msg_sender.go
msgtest/sdk_user_simulator/listener.go

fix: add SetListener in NewSendMsgUser

---

.github/workflows/merge-from-milestone.yml

feat: improve milestone merge workflows.

---

internal/relation/notification.go
open_im_sdk/userRelated.go

Fixes https://github.com/openimsdk/open-im-server/issues/3419

fix: Can`t send notification in import_friend

---

pkg/syncer/version_synchronizer.go

fix: solve lose uid kv when incr Sync.

---

.github/workflows/sdk-releaser.yml

fix: update version file in sdk releaser in v3.8.3-patch branch.

---

.github/workflows/sdk-releaser.yml

fix: update version file in sdk releaser in pre-release-v3.8.4

---

.github/workflows/update-version-file-on-release.yml

fix: remove new line in update version file in pre-release-v3.8.4.

---

.github/workflows/sdk-releaser.yml
wasm/cmd/Makefile

fix: update wasm archive have wasm_exec.js in v3.8.3-patch branch.

---

.github/workflows/sdk-releaser.yml
wasm/cmd/Makefile

fix: update wasm archive have wasm_exec.js.

---

internal/interaction/msg_sync.go
open_im_sdk/userRelated.go
pkg/syncer/version_synchronizer.go

fix: solve incorrect distinct in IncrSync and remove goroutine in syncAndTriggerReinstallMsgs func in v3.8.3-patch.

---

.github/workflows/update-version-file-on-release.yml

fix: add safe submodule in workflows in v3.8.3-patch.

---

internal/conversation_msg/api.go

fix: set correct resp in sendMsgToServer

---

pkg/db/chat_log_model.go

fix: resolve SQL injection in SearchLocalMessages in pre-release-v3.8.4

---

internal/conversation_msg/delete.go

fix: Resolved the issue where the delete message method only performs local deletion when the seq is 0.

---

pkg/db/chat_log_model.go

fix: resolve SQL injection in SearchLocalMessages

---

internal/interaction/long_conn_mgr.go

feat: add sdk version info to client conn.

---

integration_test/internal/manager/group_manager.go

fix: create group group
