go.sum
internal/conversation_msg/sdk.go

When the network environment fluctuates, the message is sent successfully. If the callback is not successful, the user tries to send the message again

V3 send message

---

internal/file/upload.go
internal/file/upload_test.go

fix: error uploading the same hash file at the same time

---

internal/conversation_msg/conversation_msg.go

fix: unread bug fix when app reinstall.

---

internal/conversation_msg/conversation_msg.go
internal/interaction/msg_sync.go

fix: remove null trigger conversation.

---

internal/user/sync.go

fix: trigger function change.

---

internal/conversation_msg/sdk.go
internal/login/init_login.go
pkg/db/chat_log_model.go
pkg/db/db_init.go
pkg/db/db_interface/databse.go
pkg/db/db_js.go
pkg/db/model_struct/data_model_struct.go
pkg/db/sending_messages_model.go
wasm/indexdb/chat_log_model.go
wasm/indexdb/sending_messages_model.go

feat: add table of sending message for set message status on weak net .

---

internal/group/group.go
internal/group/notification.go

fix: kicked user invited again into group,the group info do not changed.

---

.goreleaser.yaml

I'm currently experiencing a problem with the GoReleaser Action v4 in our GitHub Actions workflow, specifically when releasing different types of versions. While pre-releases such as v3.5.1.beta.0 are being published successfully, the action encounters failures during the publishing of official releases (e.g., v3.5.1).
🔍 What type of PR is this?
/kind documentation
/kind feature
resolves openimsdk/open-im-server#1660
👀 What this PR does / why we need it:
My pull request adheres to the code style of this project
My code requires changes to the documentation
I have updated the documentation as required
All the tests have passed
The issue is evident in the 'release actions' job of our workflow. Detailed information and logs can be found here: [Release Actions …

fix: rIssue with Asset Uploading for Official Releases in GoReleaser Action v4 - release openim version not auto build

---

internal/conversation_msg/conversation_notification.go
internal/conversation_msg/sdk.go
internal/friend/friend.go
internal/full/open_im_sdk_full.go
internal/group/group.go
internal/user/user.go
pkg/common/trigger_channel.go

Release v3.5 conversation's info update

---

internal/group/sdk.go
pkg/db/db_interface/databse.go
pkg/db/super_group_model.go

<br>
Fixes #https://github.com/openimsdk/open-im-sdk-flutter/issues/131

fix: remove some code to avoid creating group errors..

---

open_im_sdk/caller.go

feat: CheckResourceLoad when Synccall

---

internal/conversation_msg/sdk.go
open_im_sdk/conversation_msg.go
testv2/conversation_test.go

fix: add the parameter "isOnlineOnly" to the "sendMessage" method.

---

internal/group/notification.go
pkg/constant/constant.go
pkg/constant/group.go

feat: constant

---

pkg/db/model_struct/data_model_struct.go
pkg/db/version_sync.go
wasm/cmd/main.go
wasm/wasm_wrapper/wasm_friend.go

fix: update table field in version_sync and update method implement in wasm.

fix: update featute implement in wasm

---

wasm/indexdb/version_sync.go

fix: update uncorrect error use.

fix: update uncorrect error use.

---

internal/friend/friend.go
internal/friend/notification.go
internal/friend/sdk.go

feat: correct concurrecy in friend module.

feat: correct concurrecy in friend module.

---

internal/interaction/msg_sync.go
pkg/db/chat_log_model.go
pkg/db/db_interface/databse.go
wasm/indexdb/chat_log_model.go

feat: implement checkConversation seq.

feat: implement checkConversation seq.

---

go.mod
go.sum
internal/group/notification.go

* refactor: optimize conversation notification structure.
* optmize donotification structure in conversation.
* remove unnecessary contents.
* update log level and unnecessary wrap.
* fix: update uncorrect contents.
* feat: update go mod dependency version to latest.
Fixes #

bump: update go mod dependency version to latest. (#632)

---

go.mod
go.sum
internal/group/notification.go
internal/group/sdk.go
pkg/datafetcher/datafetcher.go

feat: merge main bug fix to main.

---

.github/workflows/go-build-test.yml
integration_test/internal/checker/counter.go
integration_test/internal/config/limit.go
integration_test/main.go

feat: test Workflow

---

internal/conversation_msg/notification.go
internal/conversation_msg/read_drawing.go
internal/group/group.go
internal/relation/relation.go
pkg/constant/constant.go

fix: update the latest message when group member's changed.

---

go.mod
go.sum

feat: implement default logger when no init.

---

internal/group/notification.go

Fixes #753
After being removed as a group admin, delete group requests.

fix: After being removed as a group admin, delete group requests

---

go.mod
internal/conversation_msg/message_check.go
internal/group/cache.go
internal/group/group.go
internal/relation/relation.go
internal/relation/sync.go
internal/user/user.go
pkg/db/group_member_model.go
test/long_conn_test.go

Fixes #
Fix local cache: user cache and group member cache

Fix local cache: user cache and group member cache

---

pkg/db/chat_log_model.go

fix: change the table name and add escaping.

---

internal/conversation_msg/conversation.go
internal/conversation_msg/conversation_msg.go
internal/conversation_msg/message_check.go
internal/conversation_msg/message_check_test.go
internal/conversation_msg/stream_msg.go
internal/interaction/msg_sync.go

fix: get reverse history message change.

---

go.mod
go.sum
internal/conversation_msg/message_check.go

fix: go mod dep repo update and fix reverse fetch message duplicate.

---

internal/conversation_msg/api.go
internal/conversation_msg/conversation.go
internal/conversation_msg/message_check.go
internal/user/api.go
internal/user/user.go
pkg/cache/manager.go

fix: login user's info maybe empty when app reinstall.

---

internal/conversation_msg/conversation.go

fix: search message do not filter voice message when keyword is empty.

---

go.mod
go.sum
internal/conversation_msg/api.go
internal/conversation_msg/conversation.go
internal/conversation_msg/conversation_msg.go
internal/conversation_msg/conversion.go
internal/conversation_msg/message_check.go
internal/conversation_msg/read_drawing.go
internal/interaction/long_conn_mgr.go
internal/interaction/msg_sync.go
internal/user/user.go
open_im_sdk/conversation_msg.go
pkg/cache/conversation_seq_cache.go
pkg/cache/user_cache.go
pkg/constant/constant.go
pkg/sdk_params_callback/conversation_msg_sdk_struct.go
pkg/sdkerrs/code.go
pkg/sdkerrs/predefine.go
test/conversation_test.go
test/create_msg_test.go

feat: add a function to quickly retrieve the context messages for a given message.

---

internal/conversation_msg/delete.go

fix: Resolved the issue where the delete message method only performs local deletion when the seq is 0 in pre-release-v3.8.4.
